// ============================================================
//  GeoQuest — Data: Countries & Geographic Locations
// ============================================================

const COUNTRIES = [
  { name: "Afghanistan", capital: "Kabul", code: "af" },
  { name: "Albania", capital: "Tirana", code: "al" },
  { name: "Algeria", capital: "Algiers", code: "dz" },
  { name: "Argentina", capital: "Buenos Aires", code: "ar" },
  { name: "Armenia", capital: "Yerevan", code: "am" },
  { name: "Australia", capital: "Canberra", code: "au" },
  { name: "Austria", capital: "Vienna", code: "at" },
  { name: "Azerbaijan", capital: "Baku", code: "az" },
  { name: "Bangladesh", capital: "Dhaka", code: "bd" },
  { name: "Belarus", capital: "Minsk", code: "by" },
  { name: "Belgium", capital: "Brussels", code: "be" },
  { name: "Bolivia", capital: "Sucre", code: "bo" },
  { name: "Bosnia and Herzegovina", capital: "Sarajevo", code: "ba" },
  { name: "Brazil", capital: "Brasília", code: "br" },
  { name: "Bulgaria", capital: "Sofia", code: "bg" },
  { name: "Cambodia", capital: "Phnom Penh", code: "kh" },
  { name: "Cameroon", capital: "Yaoundé", code: "cm" },
  { name: "Canada", capital: "Ottawa", code: "ca" },
  { name: "Chile", capital: "Santiago", code: "cl" },
  { name: "China", capital: "Beijing", code: "cn" },
  { name: "Colombia", capital: "Bogotá", code: "co" },
  { name: "Croatia", capital: "Zagreb", code: "hr" },
  { name: "Cuba", capital: "Havana", code: "cu" },
  { name: "Czech Republic", capital: "Prague", code: "cz" },
  { name: "Denmark", capital: "Copenhagen", code: "dk" },
  { name: "Ecuador", capital: "Quito", code: "ec" },
  { name: "Egypt", capital: "Cairo", code: "eg" },
  { name: "Ethiopia", capital: "Addis Ababa", code: "et" },
  { name: "Finland", capital: "Helsinki", code: "fi" },
  { name: "France", capital: "Paris", code: "fr" },
  { name: "Georgia", capital: "Tbilisi", code: "ge" },
  { name: "Germany", capital: "Berlin", code: "de" },
  { name: "Ghana", capital: "Accra", code: "gh" },
  { name: "Greece", capital: "Athens", code: "gr" },
  { name: "Guatemala", capital: "Guatemala City", code: "gt" },
  { name: "Hungary", capital: "Budapest", code: "hu" },
  { name: "Iceland", capital: "Reykjavik", code: "is" },
  { name: "India", capital: "New Delhi", code: "in" },
  { name: "Indonesia", capital: "Jakarta", code: "id" },
  { name: "Iran", capital: "Tehran", code: "ir" },
  { name: "Iraq", capital: "Baghdad", code: "iq" },
  { name: "Ireland", capital: "Dublin", code: "ie" },
  { name: "Israel", capital: "Jerusalem", code: "il" },
  { name: "Italy", capital: "Rome", code: "it" },
  { name: "Jamaica", capital: "Kingston", code: "jm" },
  { name: "Japan", capital: "Tokyo", code: "jp" },
  { name: "Jordan", capital: "Amman", code: "jo" },
  { name: "Kazakhstan", capital: "Astana", code: "kz" },
  { name: "Kenya", capital: "Nairobi", code: "ke" },
  { name: "Kuwait", capital: "Kuwait City", code: "kw" },
  { name: "Kyrgyzstan", capital: "Bishkek", code: "kg" },
  { name: "Laos", capital: "Vientiane", code: "la" },
  { name: "Latvia", capital: "Riga", code: "lv" },
  { name: "Lebanon", capital: "Beirut", code: "lb" },
  { name: "Libya", capital: "Tripoli", code: "ly" },
  { name: "Lithuania", capital: "Vilnius", code: "lt" },
  { name: "Luxembourg", capital: "Luxembourg City", code: "lu" },
  { name: "Malaysia", capital: "Kuala Lumpur", code: "my" },
  { name: "Mexico", capital: "Mexico City", code: "mx" },
  { name: "Moldova", capital: "Chișinău", code: "md" },
  { name: "Mongolia", capital: "Ulaanbaatar", code: "mn" },
  { name: "Morocco", capital: "Rabat", code: "ma" },
  { name: "Mozambique", capital: "Maputo", code: "mz" },
  { name: "Myanmar", capital: "Naypyidaw", code: "mm" },
  { name: "Nepal", capital: "Kathmandu", code: "np" },
  { name: "Netherlands", capital: "Amsterdam", code: "nl" },
  { name: "New Zealand", capital: "Wellington", code: "nz" },
  { name: "Nicaragua", capital: "Managua", code: "ni" },
  { name: "Nigeria", capital: "Abuja", code: "ng" },
  { name: "North Korea", capital: "Pyongyang", code: "kp" },
  { name: "Norway", capital: "Oslo", code: "no" },
  { name: "Oman", capital: "Muscat", code: "om" },
  { name: "Pakistan", capital: "Islamabad", code: "pk" },
  { name: "Panama", capital: "Panama City", code: "pa" },
  { name: "Paraguay", capital: "Asunción", code: "py" },
  { name: "Peru", capital: "Lima", code: "pe" },
  { name: "Philippines", capital: "Manila", code: "ph" },
  { name: "Poland", capital: "Warsaw", code: "pl" },
  { name: "Portugal", capital: "Lisbon", code: "pt" },
  { name: "Qatar", capital: "Doha", code: "qa" },
  { name: "Romania", capital: "Bucharest", code: "ro" },
  { name: "Russia", capital: "Moscow", code: "ru" },
  { name: "Saudi Arabia", capital: "Riyadh", code: "sa" },
  { name: "Senegal", capital: "Dakar", code: "sn" },
  { name: "Serbia", capital: "Belgrade", code: "rs" },
  { name: "Singapore", capital: "Singapore", code: "sg" },
  { name: "Slovakia", capital: "Bratislava", code: "sk" },
  { name: "Slovenia", capital: "Ljubljana", code: "si" },
  { name: "Somalia", capital: "Mogadishu", code: "so" },
  { name: "South Africa", capital: "Pretoria", code: "za" },
  { name: "South Korea", capital: "Seoul", code: "kr" },
  { name: "Spain", capital: "Madrid", code: "es" },
  { name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", code: "lk" },
  { name: "Sudan", capital: "Khartoum", code: "sd" },
  { name: "Sweden", capital: "Stockholm", code: "se" },
  { name: "Switzerland", capital: "Bern", code: "ch" },
  { name: "Syria", capital: "Damascus", code: "sy" },
  { name: "Taiwan", capital: "Taipei", code: "tw" },
  { name: "Tajikistan", capital: "Dushanbe", code: "tj" },
  { name: "Tanzania", capital: "Dodoma", code: "tz" },
  { name: "Thailand", capital: "Bangkok", code: "th" },
  { name: "Tunisia", capital: "Tunis", code: "tn" },
  { name: "Turkey", capital: "Ankara", code: "tr" },
  { name: "Turkmenistan", capital: "Ashgabat", code: "tm" },
  { name: "Uganda", capital: "Kampala", code: "ug" },
  { name: "Ukraine", capital: "Kyiv", code: "ua" },
  { name: "United Arab Emirates", capital: "Abu Dhabi", code: "ae" },
  { name: "United Kingdom", capital: "London", code: "gb" },
  { name: "United States", capital: "Washington, D.C.", code: "us" },
  { name: "Uruguay", capital: "Montevideo", code: "uy" },
  { name: "Uzbekistan", capital: "Tashkent", code: "uz" },
  { name: "Venezuela", capital: "Caracas", code: "ve" },
  { name: "Vietnam", capital: "Hanoi", code: "vn" },
  { name: "Yemen", capital: "Sana'a", code: "ye" },
  { name: "Zambia", capital: "Lusaka", code: "zm" },
  { name: "Zimbabwe", capital: "Harare", code: "zw" },
];

// Images use picsum.photos as a guaranteed-working placeholder CDN,
// paired with a real Wikimedia URL that tries first.
// The onerror fallback in HTML handles broken Wikimedia links gracefully.
const GEO_LOCATIONS = [
  {
    id: "everest",
    name: "Mount Everest",
    lat: 27.9881,
    lng: 86.9250,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg/480px-Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg",
    fallbackUrl: "https://picsum.photos/seed/everest/480/300",
    hint: "World's highest peak — Nepal/Tibet border"
  },
  {
    id: "amazon",
    name: "Amazon River",
    lat: -3.4653,
    lng: -62.2159,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Amazonriverpool.jpg/480px-Amazonriverpool.jpg",
    fallbackUrl: "https://picsum.photos/seed/amazon/480/300",
    hint: "World's largest river by discharge — South America"
  },
  {
    id: "victoria_falls",
    name: "Victoria Falls",
    lat: -17.9249,
    lng: 25.8572,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Victoria_Falls._Zimbabwe.jpg/480px-Victoria_Falls._Zimbabwe.jpg",
    fallbackUrl: "https://picsum.photos/seed/victoria/480/300",
    hint: "Massive waterfall on the Zambezi River"
  },
  {
    id: "sahara",
    name: "Sahara Desert",
    lat: 23.4162,
    lng: 25.6628,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/GoldenSahara2.jpg/480px-GoldenSahara2.jpg",
    fallbackUrl: "https://picsum.photos/seed/sahara/480/300",
    hint: "World's largest hot desert — North Africa"
  },
  {
    id: "great_barrier_reef",
    name: "Great Barrier Reef",
    lat: -18.2871,
    lng: 147.6992,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Coral_reef_at_palmyra.jpg/480px-Coral_reef_at_palmyra.jpg",
    fallbackUrl: "https://picsum.photos/seed/reef/480/300",
    hint: "World's largest coral reef — off northeastern Australia"
  },
  {
    id: "nile",
    name: "Nile River",
    lat: 26.8206,
    lng: 30.8025,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nile_River_and_delta_from_orbit.jpg/480px-Nile_River_and_delta_from_orbit.jpg",
    fallbackUrl: "https://picsum.photos/seed/nile/480/300",
    hint: "Longest river in Africa — flows through Egypt"
  },
  {
    id: "baikal",
    name: "Lake Baikal",
    lat: 53.5587,
    lng: 108.1650,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Baikal_1.jpg/480px-Baikal_1.jpg",
    fallbackUrl: "https://picsum.photos/seed/baikal/480/300",
    hint: "World's deepest lake — Siberia, Russia"
  },
  {
    id: "kilimanjaro",
    name: "Mount Kilimanjaro",
    lat: -3.0674,
    lng: 37.3556,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Kilimanjaro_from_the_east_%28crop%29.jpg/480px-Kilimanjaro_from_the_east_%28crop%29.jpg",
    fallbackUrl: "https://picsum.photos/seed/kili/480/300",
    hint: "Africa's highest peak — Tanzania"
  },
  {
    id: "grand_canyon",
    name: "Grand Canyon",
    lat: 36.1069,
    lng: -112.1129,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Dawn_on_the_S_rim_of_the_Grand_Canyon_%288645178272%29.jpg/480px-Dawn_on_the_S_rim_of_the_Grand_Canyon_%288645178272%29.jpg",
    fallbackUrl: "https://picsum.photos/seed/canyon/480/300",
    hint: "Carved by the Colorado River — Arizona, USA"
  },
  {
    id: "dead_sea",
    name: "Dead Sea",
    lat: 31.5590,
    lng: 35.4732,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Dead_Sea_by_David_Shankbone.jpg/480px-Dead_Sea_by_David_Shankbone.jpg",
    fallbackUrl: "https://picsum.photos/seed/deadsea/480/300",
    hint: "World's lowest point on land — Jordan/Israel"
  },
  {
    id: "gobi",
    name: "Gobi Desert",
    lat: 42.5903,
    lng: 103.4543,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Gobi_Desert_Yol_Valley.jpg/480px-Gobi_Desert_Yol_Valley.jpg",
    fallbackUrl: "https://picsum.photos/seed/gobi/480/300",
    hint: "Asia's largest desert — China and Mongolia"
  },
  {
    id: "galapagos",
    name: "Galápagos Islands",
    lat: -0.9538,
    lng: -90.9656,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Gal%C3%A1pagos_hawk_%28Buteo_galapagoensis%29.jpg/480px-Gal%C3%A1pagos_hawk_%28Buteo_galapagoensis%29.jpg",
    fallbackUrl: "https://picsum.photos/seed/galapagos/480/300",
    hint: "Volcanic islands in the Pacific — off Ecuador"
  },
  {
    id: "niagara",
    name: "Niagara Falls",
    lat: 43.0799,
    lng: -79.0747,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Niagara_Falls_%28pixinn.net%29.jpg/480px-Niagara_Falls_%28pixinn.net%29.jpg",
    fallbackUrl: "https://picsum.photos/seed/niagara/480/300",
    hint: "Iconic waterfall — USA/Canada border"
  },
  {
    id: "titicaca",
    name: "Lake Titicaca",
    lat: -15.9254,
    lng: -69.3354,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Lake_Titicaca_%28Bolivia%29.jpg/480px-Lake_Titicaca_%28Bolivia%29.jpg",
    fallbackUrl: "https://picsum.photos/seed/titicaca/480/300",
    hint: "World's highest navigable lake — Peru/Bolivia"
  },
  {
    id: "atacama",
    name: "Atacama Desert",
    lat: -23.6330,
    lng: -69.3333,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Atacama_Desert.jpg/480px-Atacama_Desert.jpg",
    fallbackUrl: "https://picsum.photos/seed/atacama/480/300",
    hint: "World's driest non-polar desert — Chile"
  },
  {
    id: "yangtze",
    name: "Yangtze River",
    lat: 30.7219,
    lng: 111.2863,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Yangtze_River_at_Yichang.jpg/480px-Yangtze_River_at_Yichang.jpg",
    fallbackUrl: "https://picsum.photos/seed/yangtze/480/300",
    hint: "Longest river in Asia — flows through China"
  },
  {
    id: "fuji",
    name: "Mount Fuji",
    lat: 35.3606,
    lng: 138.7274,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/080103_hakkai_fuji.jpg/480px-080103_hakkai_fuji.jpg",
    fallbackUrl: "https://picsum.photos/seed/fuji/480/300",
    hint: "Japan's iconic snow-capped volcanic peak"
  },
  {
    id: "caspian",
    name: "Caspian Sea",
    lat: 42.0000,
    lng: 51.0000,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Caspian_Sea_from_orbit.jpg/480px-Caspian_Sea_from_orbit.jpg",
    fallbackUrl: "https://picsum.photos/seed/caspian/480/300",
    hint: "World's largest inland body of water"
  },
  {
    id: "congo",
    name: "Congo River",
    lat: -0.7893,
    lng: 24.5085,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Congo_River_Congo_DR_Congo.jpg/480px-Congo_River_Congo_DR_Congo.jpg",
    fallbackUrl: "https://picsum.photos/seed/congo/480/300",
    hint: "World's deepest river — Central Africa"
  },
  {
    id: "serengeti",
    name: "Serengeti Plains",
    lat: -2.3333,
    lng: 34.8333,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Serengeti_Masai_Mara_Plain_Africa.jpg/480px-Serengeti_Masai_Mara_Plain_Africa.jpg",
    fallbackUrl: "https://picsum.photos/seed/serengeti/480/300",
    hint: "Famous for the Great Migration — Tanzania"
  },
  {
    id: "matterhorn",
    name: "Matterhorn",
    lat: 45.9766,
    lng: 7.6586,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Matterhorn_as_seen_from_Zermatt%2C_Wallis%2C_Switzerland%2C_2012_August.jpg/480px-Matterhorn_as_seen_from_Zermatt%2C_Wallis%2C_Switzerland%2C_2012_August.jpg",
    fallbackUrl: "https://picsum.photos/seed/matterhorn/480/300",
    hint: "Iconic pyramidal peak — Swiss/Italian border"
  },
  {
    id: "danube",
    name: "Danube River",
    lat: 45.2671,
    lng: 29.6753,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Danube_at_Budapest.jpg/480px-Danube_at_Budapest.jpg",
    fallbackUrl: "https://picsum.photos/seed/danube/480/300",
    hint: "Second longest river in Europe"
  },
  {
    id: "patagonia",
    name: "Patagonia",
    lat: -45.8667,
    lng: -67.5000,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Glaciar_Perito_Moreno_-_Patagonia_-_Argentina_-_01A.jpg/480px-Glaciar_Perito_Moreno_-_Patagonia_-_Argentina_-_01A.jpg",
    fallbackUrl: "https://picsum.photos/seed/patagonia/480/300",
    hint: "Vast wilderness at the southern tip of South America"
  },
  {
    id: "great_rift",
    name: "Great Rift Valley",
    lat: 1.0,
    lng: 36.5,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Aerial_view_of_the_Southern_Rift_Valley%2C_Ethiopia.jpg/480px-Aerial_view_of_the_Southern_Rift_Valley%2C_Ethiopia.jpg",
    fallbackUrl: "https://picsum.photos/seed/rift/480/300",
    hint: "Major geological feature — East Africa"
  },
  {
    id: "fjords",
    name: "Norwegian Fjords",
    lat: 60.9553,
    lng: 6.7492,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Geirangerfjord_2.jpg/480px-Geirangerfjord_2.jpg",
    fallbackUrl: "https://picsum.photos/seed/fjord/480/300",
    hint: "Dramatic sea inlets carved by glaciers — Norway"
  },
];
